# Generated by Django 4.2 on 2023-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_book_photo_author_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
